variables:
  AUDIT_AWS_ELB_ALERT_LIST:
    description: List of specific alerts to run. Default is to run those listed here.
    required: true
    type: array
    default:
      - elb-old-ssl-policy
  AUDIT_AWS_ELB_ALERT_RECIPIENT:
    description: Enter the default email recipient for alerts?
    required: true
    type: string
    default:
  AUDIT_AWS_ELB_ALLOW_EMPTY:
    description: Receive empty reports? ( true / false ) Default is false.
    required: true
    type: string
    default: false
  AUDIT_AWS_ELB_PAYLOAD_TYPE:
    description: Send reports as json or text? Default of json recommended.
    required: true
    type: string
    default: "json"
  AUDIT_AWS_ELB_SEND_ON:
    description: Always send a report or only when there are changes? ( always or change ) Default is change .
    required: true
    type: string
    default: "change"
  AUDIT_AWS_ELB_REGIONS:
    description: List of AWS regions to check. Default is us-east-1, us-west-1, us-west-2.
    required: true
    type: array
    default:
        - us-east-1
        - us-west-1
        - us-west-2
#       - ap-south-1
#       - ap-northeast-1
#       - ap-northeast-2
#       - ap-southeast-1
#       - ap-southeast-2
#       - eu-central-1
#       - eu-west-1
#       - sa-east-1
